-- Lunaria manual apply bundle: 020 -> 021
-- Generated by: npm run character:sql-pack
-- Paste into Supabase SQL Editor only after confirming the target project.
-- Source of truth remains supabase/migrations/*.sql.

-- ============================================================================
-- 020_user_items.sql
-- ============================================================================
-- migration 020: user items ownership projection
--
-- Purpose:
--   Introduce lunaria_user_items as the future source of truth for item ownership,
--   while remaining compatible with the existing gacha tables.
--
-- Notes:
--   - This migration is a candidate file. Do not apply to production until reviewed.
--   - Existing gacha inventory/history tables are preserved.
--   - Backfill reads from lunaria_gacha_inventory and lunaria_gacha_history.
--   - Item IDs reference lunaria_gacha_pool(id) because the current schema does not
--     yet have a separate lunaria_items catalog.

create table if not exists public.lunaria_user_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.lunaria_users(id) on delete cascade,
  pool_id uuid not null references public.lunaria_gacha_pool(id) on delete cascade,

  obtained_from text not null default 'gacha' check (obtained_from in (
    'gacha', 'free_grant', 'event_reward', 'subscription_grant', 'admin_grant', 'streak_bonus', 'migration'
  )),
  obtained_at timestamptz not null default now(),
  is_equipped boolean not null default false,

  duplicate_count integer not null default 0 check (duplicate_count >= 0),
  last_obtained_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  unique (user_id, pool_id)
);

alter table public.lunaria_user_items enable row level security;

drop policy if exists "lunaria_own_user_items_select" on public.lunaria_user_items;
create policy "lunaria_own_user_items_select"
  on public.lunaria_user_items
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "lunaria_own_user_items_insert" on public.lunaria_user_items;
create policy "lunaria_own_user_items_insert"
  on public.lunaria_user_items
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "lunaria_own_user_items_update" on public.lunaria_user_items;
create policy "lunaria_own_user_items_update"
  on public.lunaria_user_items
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "lunaria_own_user_items_delete" on public.lunaria_user_items;
create policy "lunaria_own_user_items_delete"
  on public.lunaria_user_items
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create index if not exists lunaria_user_items_user_obtained_idx
  on public.lunaria_user_items(user_id, obtained_at desc)
  where deleted_at is null;

create index if not exists lunaria_user_items_pool_idx
  on public.lunaria_user_items(pool_id)
  where deleted_at is null;

create index if not exists lunaria_user_items_user_equipped_idx
  on public.lunaria_user_items(user_id, is_equipped)
  where is_equipped and deleted_at is null;

create or replace function public.lunaria_touch_user_items_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lunaria_user_items_touch_updated_at on public.lunaria_user_items;
create trigger lunaria_user_items_touch_updated_at
  before update on public.lunaria_user_items
  for each row execute function public.lunaria_touch_user_items_updated_at();

-- Backfill ownership from the existing unique inventory table.
insert into public.lunaria_user_items (
  user_id,
  pool_id,
  obtained_from,
  obtained_at,
  duplicate_count,
  last_obtained_at,
  metadata,
  created_at,
  updated_at
)
select
  inv.user_id,
  inv.pool_id,
  'migration' as obtained_from,
  inv.acquired_at as obtained_at,
  coalesce(hist.duplicate_count, 0) as duplicate_count,
  coalesce(hist.last_obtained_at, inv.acquired_at) as last_obtained_at,
  jsonb_build_object('source', 'lunaria_gacha_inventory') as metadata,
  now() as created_at,
  now() as updated_at
from public.lunaria_gacha_inventory inv
left join lateral (
  select
    count(*) filter (where h.was_duplicate) as duplicate_count,
    max(h.pulled_at) as last_obtained_at
  from public.lunaria_gacha_history h
  where h.user_id = inv.user_id
    and h.pool_id = inv.pool_id
) hist on true
on conflict (user_id, pool_id) do update
  set duplicate_count = greatest(lunaria_user_items.duplicate_count, excluded.duplicate_count),
      last_obtained_at = greatest(lunaria_user_items.last_obtained_at, excluded.last_obtained_at),
      metadata = lunaria_user_items.metadata || excluded.metadata,
      updated_at = now();

-- Verification queries:
-- select count(*) from public.lunaria_user_items;
-- select ui.user_id, gp.name, gp.rarity, ui.duplicate_count
--   from public.lunaria_user_items ui
--   join public.lunaria_gacha_pool gp on gp.id = ui.pool_id
--  order by ui.obtained_at desc
--  limit 20;

-- ============================================================================
-- 021_character_states.sql
-- ============================================================================
-- migration 021: character state scaffold
--
-- Purpose:
--   Add a small, future-friendly state table for Lunaria's current visible state
--   without coupling chat text, diary, memory, or gacha history together.
--
-- Notes:
--   - This migration is a candidate file. Do not apply to production until reviewed.
--   - It intentionally avoids a character_profiles foreign key because that catalog
--     is still design-only in this repo.
--   - Item references point to lunaria_gacha_pool(id) for compatibility with the
--     current Phase G schema. A later catalog split can migrate these columns.

create table if not exists public.lunaria_character_states (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.lunaria_users(id) on delete cascade,
  character_profile_id text not null default 'lunaria',

  current_outfit_pool_id uuid references public.lunaria_gacha_pool(id) on delete set null,
  current_background_pool_id uuid references public.lunaria_gacha_pool(id) on delete set null,
  current_diary_skin_pool_id uuid references public.lunaria_gacha_pool(id) on delete set null,
  equipped_accessory_pool_ids uuid[] not null default '{}',
  room_item_pool_ids uuid[] not null default '{}',

  current_expression text not null default 'normal',
  current_motion text not null default 'idle',

  affinity_level integer not null default 0 check (affinity_level >= 0 and affinity_level <= 100),
  affinity_streak_days integer not null default 0 check (affinity_streak_days >= 0),

  unlocked_expressions text[] not null default array['normal','gentle_smile','thinking','sad','serious'],
  unlocked_motions text[] not null default array['idle','nod','tilt_head'],
  unlocked_voices text[] not null default '{}',

  last_interaction_at timestamptz,
  last_diary_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,

  unique (user_id, character_profile_id)
);

alter table public.lunaria_character_states enable row level security;

drop policy if exists "lunaria_own_character_states_select" on public.lunaria_character_states;
create policy "lunaria_own_character_states_select"
  on public.lunaria_character_states
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "lunaria_own_character_states_insert" on public.lunaria_character_states;
create policy "lunaria_own_character_states_insert"
  on public.lunaria_character_states
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "lunaria_own_character_states_update" on public.lunaria_character_states;
create policy "lunaria_own_character_states_update"
  on public.lunaria_character_states
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "lunaria_own_character_states_delete" on public.lunaria_character_states;
create policy "lunaria_own_character_states_delete"
  on public.lunaria_character_states
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create index if not exists lunaria_character_states_user_profile_idx
  on public.lunaria_character_states(user_id, character_profile_id)
  where deleted_at is null;

create index if not exists lunaria_character_states_last_interaction_idx
  on public.lunaria_character_states(user_id, last_interaction_at desc)
  where deleted_at is null;

create or replace function public.lunaria_touch_character_states_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lunaria_character_states_touch_updated_at on public.lunaria_character_states;
create trigger lunaria_character_states_touch_updated_at
  before update on public.lunaria_character_states
  for each row execute function public.lunaria_touch_character_states_updated_at();

-- Create default Lunaria state rows for existing users. Do not infer equipment.
insert into public.lunaria_character_states (
  user_id,
  character_profile_id,
  metadata
)
select
  u.id,
  'lunaria',
  jsonb_build_object('source', '021_character_states_default_seed')
from public.lunaria_users u
on conflict (user_id, character_profile_id) do nothing;

-- Verification queries:
-- select count(*) from public.lunaria_character_states;
-- select user_id, character_profile_id, current_expression, current_motion, affinity_level
--   from public.lunaria_character_states
--  order by updated_at desc
--  limit 20;

-- ============================================================================
-- Post-apply verification queries for 020/021
-- ============================================================================

-- 1. New tables should exist.
select table_name
  from information_schema.tables
 where table_schema = 'public'
   and table_name in ('lunaria_user_items', 'lunaria_character_states')
 order by table_name;

-- 2. RLS should be enabled.
select relname, relrowsecurity
  from pg_class
 where relname in ('lunaria_user_items', 'lunaria_character_states')
 order by relname;

-- 3. User items should expose expected columns.
select column_name
  from information_schema.columns
 where table_schema = 'public'
   and table_name = 'lunaria_user_items'
   and column_name in (
     'user_id', 'pool_id', 'obtained_from', 'obtained_at',
     'is_equipped', 'duplicate_count', 'last_obtained_at', 'metadata', 'deleted_at'
   )
 order by column_name;

-- 4. Character states should expose expected columns.
select column_name
  from information_schema.columns
 where table_schema = 'public'
   and table_name = 'lunaria_character_states'
   and column_name in (
     'user_id', 'character_profile_id', 'current_outfit_pool_id',
     'current_background_pool_id', 'current_expression', 'current_motion',
     'affinity_level', 'unlocked_expressions', 'unlocked_motions', 'metadata', 'deleted_at'
   )
 order by column_name;

-- 5. Backfill sanity check.
select
  (select count(*) from public.lunaria_gacha_inventory) as old_inventory_rows,
  (select count(*) from public.lunaria_user_items) as user_item_rows,
  (select count(*) from public.lunaria_character_states) as character_state_rows;

-- 6. Policy names should exist.
select tablename, policyname, cmd
  from pg_policies
 where schemaname = 'public'
   and tablename in ('lunaria_user_items', 'lunaria_character_states')
 order by tablename, policyname;
